# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- 
- task: UiPathPack@4
  inputs:
    versionType: 'CurrentVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    splitOutput: true
    orchestratorConnection: 'DemoDevops'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Information'
- task: UiPathTest@4
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'DemoDevops'
    folderName: 'abc'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ArtifactSamplebuild'
    publishLocation: 'Container'